# valine
valine_app_id: "将这个字符串替换为你的valine用AppID"
valine_app_key: "替换为Valine用AppKey"
valine_common_place_holder: "替换为占位符"

# footer, html code
footer: 
  - '<a href="{{ site.baseurl }}/static/xml/rss.xml">RSS</a> | '
  - 'Themed by <a href="https://github.com/moi-mo/UMPaper">UMPaper</a>'